### PR TITLE
AndroidX support

### LINKED ISSUE #9: migrate to AndroidX

### PR DESCRIPTION
**Pull request by Gurkengewuerz**
Support for AndroidX with updated compile and target version bumped up to 28 in order to fix #9.
First merging into develop for more testing.

In order to run it properly the PR https://github.com/droibit/CustomTabsLauncher/pull/3 in the library have to be merged first with a new version tag into master.
After that i or @droibit can also update the version tag of the library in the gradle file.

Example worked perfect for me with the new version of the pr.

If you want to give all a try here is a version with the gradle file updated to my test branch https://github.com/Gurkengewuerz/flutter_custom_tabs/tree/workaround

### CODE REVIEW

**Comment by Gurkengewuerz** [comment]
@droibit any updates? We need AndroidX support for flutter. Many plugins are updating now (such as shared_preferences or the complete firebase suite) and if custom tabs get no upgrade to androidx no user can use the package anymore. And also the AndroidX Library is much better than the Android support library.

**Comment by Gurkengewuerz** [comment]
Now where https://github.com/droibit/CustomTabsLauncher/pull/3 is merged (thanks :)) i or you have to update https://github.com/droibit/flutter_custom_tabs/blob/master/android/build.gradle#L41 to the new version (i think 🤔)

**Comment by droibit** [comment]
@Gurkengewuerz   
Thanks again, your PR 🙇 
I updated CustomTabsLauncher to `v1.4.0`, so could you update the line you point to below?
- `api 'com.github.droibit.customtabslauncher:launcher:1.4.0'`

**Comment by Gurkengewuerz** [comment]
> @Gurkengewuerz
> Thanks again, your PR 🙇
> I updated CustomTabsLauncher to `v1.4.0`, so could you update the line you point to below?
> 
> * `api 'com.github.droibit.customtabslauncher:launcher:1.4.0'`

Sure, already done! Thanks!

**Comment by droibit** [comment]
Thanks, I will upload this package to pub now!

**Pull request merged**
