### PR TITLE
Add closeAllIfPossible() method

### PR DESCRIPTION
**Pull request by em-yhoshino**
# What is this?
I have added closeAllIfPossible(), which closes all launched SFSafariViewControllers via flutter_custom_tabs, to launcher.

# Before this PR

Once the app launched a SFSafariViewController via flutter_custom_tabs, it could not be closed until the user closed it. Therefore, the SFSafariViewController was masking the deep link transition.

# After this PR
The app can close all SFSafariViewController at any time.
It is especially useful before deep link transitions.

# How to use
Like this,

```
import 'package:flutter_custom_tabs/flutter_custom_tabs.dart' as custom_tabs;

await custom_tabs.launch(uriString);

// When deeplink is invoked
await custom_tabs.closeAllIfPossible();
await transition(deeplink);
```

It avoids occuring a transition behind a SFSafariViewController that is not closed by user.

# Android and web
In Android and web, empty operations have been implemented because there is no proper way to close customTabs. 
At least, Android doesn't require it in case of deep link scenario. 
This is because customTabs are automatically closed when app returns from background.

### CODE REVIEW

**Comment by em-yhoshino** [comment]
The CI failed due to the dependency specification.
How can I solve it?

I think that the refs should be specified on the develop branch because the branch to which this PR will be merged is develop.

**Comment by Aulig** [comment]
Thank you so much for this, exactly what I needed.

I had to download it locally and edit the pubspec files to get the dependencies to work like you said - not sure how to correctly fix it though so it'd work in the CI. Just wanted to thank you for this valuable feature.

**Comment by angeloborrelli** [comment]
Hello @em-yhoshino,
I really need your implementation of closeAllIfPossible() since in iOS, custom tab doesn't close after deep link and no way to close it manually so I'm trying to use your forked plugin version by putting this lines in my pubspec.yaml:
```
  flutter_custom_tabs:
    git:
      url: https://github.com/em-yhoshino/flutter_custom_tabs.git
      ref: master
```
Actually `flutter pub get` is returning this error:
```
Could not find a file named "pubspec.yaml" in https://github.com/em-yhoshino/flutter_custom_tabs.git eff797dda32aaa9bbc88af9e384f86e74f5a50d4.
pub get failed (1; Could not find a file named "pubspec.yaml" in https://github.com/em-yhoshino/flutter_custom_tabs.git eff797dda32aaa9bbc88af9e384f86e74f5a50d4.)
exit code 1
```
What am i doing wrong? Is it possible to test it or am i supposed to wait for @droibit to merge into a new officiale version? 
Thanks for letting me know.
Regards
Angelo

**Comment by droibit** [comment]
Thank you for the PR!  
I apologize for not replying for a long time.

This plugin has not been maintained for a long time
so don't worry about the error on CI.

I will fix the workflows later.

**Comment by Aulig** [comment]
> Thank you for the PR! I apologize for not replying for a long time.
> 
> This plugin has not been maintained for a long time so don't worry about the error on CI.
> 
> I will fix the workflows later.

Thank you so much for coming back to this project! Looking forward to being able to use this version (not the fork) again once it's live on pub.dev :)

**Comment by droibit** [comment]
The latest v1.11.0 with this PR has just been published on pub.dev!
- https://pub.dev/packages/flutter_custom_tabs/versions/1.1.0

Thank you for your patience.

**Comment by Aulig** [comment]
> The latest v1.11.0 with this PR has just been published on pub.dev!
> 
>     * https://pub.dev/packages/flutter_custom_tabs/versions/1.1.0
> 
> 
> Thank you for your patience.

You're the best, thank you!

**Pull request merged**
